### ISSUE TITLE
Run on HA with AppDaemon

### ISSUE THREAD

**Issue by akeslo** [marecotec/Home_Assistant_Oil_Smart_Oil_Gauge#1]
Any way to run this on HA with AppDaemon?

**Comment by marecotec** [comment]
Hi, thanks for your interest. I haven't really explored turning this into anything stronger. The work around that I produced is a specific solution to my problem. If it is of use and you want to explore this, I am happy to collaborate.

**Comment by marecotec** [comment]
Also, I fixed an issue with the ChromeDriver by adding some code to avoid an issue with ChromeDriver selection. I'll try to update the repo soon.

**Comment by akeslo** [comment]
@marecotec Thanks! Sounds like a plan, I did have some issues with ChromeDriver and ended up using webdriver_manager to manage the driver selection.  I'll fork and post my changes.
